jenkins:
  numExecutors: 12
  scmCheckoutRetryCount: 2
  mode: NORMAL

  agentProtocols:
  - "JNLP4-connect"
  - "Ping"

  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
      - id: "danibb"
        password: "HilaUval10"

security:
  remotingCLI:
    enabled: false

